#define HTS_CC "gcc"
#define HTS_CPPFLAGS "-std=c++11 -Wall -O3 -I /home/user/anaconda3/envs/atttrio/include -L /home/user/anaconda3/envs/atttrio/lib -Wl,-rpath=/home/user/anaconda3/envs/atttrio/lib"
#define HTS_CFLAGS "-Wall -g -O2 -fvisibility=hidden"
#define HTS_LDFLAGS "-fvisibility=hidden "
#define HTS_LIBS "-ldeflate -llzma -lbz2 -lz -lm   -lcurl -lcrypto"
